### ISSUE TITLE
Does not work on iPad

### ISSUE THREAD

**Issue by agugel** [kiliankoe/Karte#8]
The alert view can't be presented on an iPad, when style = .actionSheet is used.

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x105272a00>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:

**Comment by kiliankoe** [comment]
Huh, you're absolutely right. Seems like I've never tested this to run on an iPad 🤦‍♂️ 

Since I don't want to make any assumptions about your presentation, I just pushed a new commit that adds `Karte.createPicker()` which returns the `UIAlertController` instead of directly trying to present it. Can you try and see if that works out for you including the notes referred to [here](https://stackoverflow.com/questions/26039229/swift-uialertcontroller-actionsheet-ipad-ios8-crashes)? Thanks!

**Comment by agugel** [comment]
Hi Kilian, 

Thank you very much! This new method `Karte.createPicker()` works great on iPad and iPhone

` 
let sender : UIButton....

 let alertController = Karte.createPicker(destination: location)
            if let popoverController = alertController.popoverPresentationController {
                popoverController.sourceView = sender
                popoverController.sourceRect = sender.bounds
            }
            self.present(alertController, animated: true)`

Thanks for your fast response and excellent work.

Alex

**Comment by kiliankoe** [comment]
Thanks for the update! Just tagged the version and pushed 0.2.0 accordingly.
